export const PRODUCTS = [
  { id: 1,
    name: 'Chair',
    desc: 'Furniture',
    imageUrl: '../assets/1-product_500.jpg',
    price: '$2500',
  },
  { id: 2,
    name: 'Chair',
    desc: 'Furniture',
    imageUrl: '../assets/All Furniture_Living.jpg',
    price: '$2500',
  },
  { id: 3,
    name: 'Chair',
    desc: 'Furniture',
    imageUrl: '../assets/product-500x500.jpeg',
    price: '$2500',
  },
  { id: 4,
    name: 'Chair',
    desc: 'Furniture',
    imageUrl: '../assets/1-product_500.jpg',
    price: '$2500',
  },
];